config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'restaurants#index'
  
  resources :restaurants do
    member do
      patch 'star-restaurant', to: 'restaurants#give_star', as: 'star'
      delete 'unstar-restaurant', to: 'restaurants#remove_star', as: 'unstar'
    end
    
    collection do
      get 'random', to: 'restaurants#random', as: 'random'  
      get 'cuisine/:name', to: 'restaurants#cuisine_filter', as: 'cuisine'
      get 'most-popular', to: 'restaurants#most_popular', as: 'most_popular'
      get 'starred', to: 'restaurants#starred_filter', as: 'starred'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  after_create :submitter_automatic_star
    
  # Associations
  belongs_to :user
  has_many :stars
  has_many :starring_users, through: :stars, dependent: :destroy
  
  # Validation
  validates_presence_of :name, :address, :telephone_number, :cuisine
  validates_uniqueness_of :name
  validates :cuisine, 
            inclusion: { in: %w(Filipino Chinese American Korean Fastfood),
            message: "%{value} is not a valid cuisine category" }
            
  validate :check_telephone_number_format
  
  def check_telephone_number_format
    valid_phone_formats = [
      /^\+\d\d \d \d\d\d-\d\d\d\d$/,               # +63 2 123-4567
      /^\d\d \d\d\d-\d\d\d\d$/,                    # 02 123-4567
      /^\+\d\d \d \d\d\d-\d\d\d\d ext. \d\d\d$/    # +63 2 123-4567 ext. 103
    ]
    
    matched = valid_phone_formats.map do |re|
      re.match(telephone_number)
    end.any?
    unless matched
      error_msg = <<-DOC
      format is invalid<br />
      Example:<br />
        +63 2 123-4567<br />
        02 123-4567<br />
        +63 2 123-4567 ext. 103
      DOC
    
      errors.add(:telephone_number, error_msg)
    end
  end
  
  protected
  
    def submitter_automatic_star
      user = self.user
      user.starred_restaurants << self
      user.save
    end

end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :starred_restaurants, class_name: "Restaurant", 
             foreign_key: :restaurant_id, counter_cache: :stars_count
  belongs_to :starring_users, class_name: "User", foreign_key: :user_id
  
  validates_uniqueness_of :user_id, scope: :restaurant_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # Associations
  has_many :restaurants, dependent: :destroy
  has_many :stars
  has_many :starred_restaurants, through: :stars, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show,
                  :random, :cuisine_filter, :most_popular]
  before_action :verify_user, only: [:edit, :update, :destroy]
  before_action :find_params, only: [:show, :edit, :update, :destroy,
                              :give_star, :remove_star]
  
  RestaurantsPerPage = 8
  
  def index
    @restaurants = Restaurant.order(created_at: :desc)
            .paginate(:page => params[:page], :per_page => RestaurantsPerPage)
  end
  
  def show
  end
  
  def new
    @restaurant = Restaurant.new
  end
  
  def create
    @restaurant = current_user.restaurants.build(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant  
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'  
    end
  end
  
  def destroy
    @restaurant.destroy
    redirect_to root_path
  end
  
  def give_star
    @restaurant.starring_users << current_user
    redirect_to @restaurant
  end
  
  def remove_star
    @restaurant.starring_users.delete(current_user)
    redirect_to @restaurant
  end
  
  def random
    if Restaurant.count > 3
      ids = Restaurant.pluck(:id)
      @restaurants = Restaurant.find(ids.sample(3))
    else
      @restaurants = Restaurant.all
    end
    render 'index'
  end
  
  def cuisine_filter
    @restaurants = Restaurant.where('cuisine = ?', params[:name].capitalize)
        .order(stars_count: :desc)
        .paginate(:page => params[:page], :per_page => RestaurantsPerPage)
    render 'index'
  end  
  
  def most_popular
    @restaurants = Restaurant.order(stars_count: :desc)
        .paginate(:page => params[:page], :per_page => RestaurantsPerPage)
    render 'index'
  end
  
  def starred_filter
    @restaurants = current_user.starred_restaurants.order(created_at: :desc)   
        .paginate(:page => params[:page], :per_page => RestaurantsPerPage)
    render 'index'
  end
  
  private
  
    def find_params
      @restaurant = Restaurant.find(params[:id])  
    end
  
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :telephone_number, :cuisine)  
    end
    
    def verify_user
      restaurant = Restaurant.find(params[:id])
      if current_user != restaurant.user
        redirect_to root_path  
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_submitted_restaurant?(restaurant)
    user_signed_in? && current_user == restaurant.user        
  end
  
  def get_page_title
    if controller_name == 'restaurants'
      if action_name == 'random'
        return 'Random'
      elsif action_name == 'cuisine_filter'
        cuisine_name = params[:name] || ''
        return cuisine_name.capitalize + ' Cuisines'
      elsif action_name == 'most_popular'
        return 'Most Popular'
      elsif action_name == 'starred_filter'
        return 'My Starred Restaurants'
      else
        return "Home"
      end
    end
  end
  
  def get_active_if_current(path)
    current_page?(path) ? 'active' : ''
  end
  
  def get_active_for_cuisine
    controller_name == 'restaurants' && action_name == 'cuisine_filter' ?
      'active' : ''
  end
  
  def pagination_shown?
    action_name != 'random'
  end
  
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_flash_messages.html.erb
<p class="notice text-primary"><strong><%= notice %></strong></p>
<p class="alert text-danger"><strong><%= alert %></strong></p>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Kainan App", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= get_active_if_current(root_path) %>">
          <%= link_to "Home", root_path %>
        </li>
        <li class="<%= get_active_if_current(random_restaurants_path) %>">
          <%= link_to "Random", random_restaurants_path %>
        </li>
        
        <li class="<%= get_active_for_cuisine %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
             role="button" aria-haspopup="true" aria-expanded="false">
             Cuisines <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Filipino", cuisine_restaurants_path('filipino') %>
            </li>
            <li>
              <%= link_to "Chinese", cuisine_restaurants_path('chinese') %>
            </li>
            <li>
              <%= link_to "American", cuisine_restaurants_path('american') %>
            </li>
            <li>
              <%= link_to "Korean", cuisine_restaurants_path('korean') %>
            </li>
            <li>
              <%= link_to "Fastfood", cuisine_restaurants_path('fastfood') %>
            </li>
          </ul>
        </li>
        
        <li class="<%= get_active_if_current(most_popular_restaurants_path) %>">
          <%= link_to "Most Popular", most_popular_restaurants_path %>
        </li>
        
        <% if user_signed_in? %>
          <li class="<%= get_active_if_current(starred_restaurants_path) %>">
            <%= link_to "Starred Restaurants", starred_restaurants_path %>
          </li>
        <% end %>
      </ul>
      
       <% if user_signed_in? %>
          <span class="navbar-right">
          <%= link_to "Add Restaurant", new_restaurant_path, 
                  class: "btn btn-success navbar-btn navbtn-top" %>      
              
          <%= link_to "Log Out", destroy_user_session_path, method: :delete,
                  class: "btn btn-primary navbar-btn navbtn-top" %>
          </span>
        <% else %>
          <span class="navbar-right">
            <%= link_to "Login", new_user_session_path, 
                        class: "btn btn-success navbar-btn" %>
            <%= link_to "Sign Up", new_user_registration_path,
                        class: "btn btn-primary navbar-btn navbtn-top" %>
          </span>
        <% end %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>
      Kainan-App - <%= content_for?(:title) ? yield(:title) : "let's eat" %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
    
    <div class="container">
      <div class="main-container">
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, html: { class: "form-horizontal" } ) do |f| %>
  <div class="text-danger">
    <% if @restaurant.errors.any? %>
      <%= pluralize(@restaurant.errors.count, "error") %>
      prevented this restaurant from being
      <%= @restaurant.new_record? ? "added" : "updated" %>
      
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg.html_safe %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-1" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :address, class: "control-label col-sm-1" %>
    <div class="col-sm-6">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :telephone_number, class: "control-label col-sm-1" %>
    <div class="col-sm-6">
      <%= f.text_field :telephone_number, class: "form-control" %>
    </div>
  </div>
  
   <div class="form-group">
    <%= f.label :cuisine, class: "control-label col-sm-1" %>
    <div class="col-sm-6">
      <%= f.select :cuisine, 
        options_for_select([["Filipino", "Filipino"], ["Chinese", "Chinese"],
        ["American", "American"], ["Korean", "Korean"], 
        ["Fastfood", "Fastfood"]], selected: f.object.cuisine),
        { include_blank: "Select Cuisine" }, class: "form-control" %>
    </div>
  </div>
    
  <% if @restaurant.new_record? %>    
    <%= f.submit "Add Restaurant", class: "btn btn-success btn-lg", 
          data: { disable_with: "Adding Restaurant..." } %>
  <% else %>
    <%= f.submit "Update Restaurant", class: "btn btn-success btn-lg", 
          data: { disable_with: "Updating Restaurant..." } %>
  <% end %>
<% end %>

app/views/restaurants/edit.html.erb
<% content_for(:title) do %>
  Edit Restaurant
<% end %>

<h2>Edit Restaurant <%= @restaurant.name %></h2>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<% content_for(:title) do %>
 <%= get_page_title %>
<% end %>

<div class="row">
  
  <div class="col-lg-4 col-lg-push-8">
    <div class="panel side-panel">
      <div class="panel-heading resto-panel-heading">
        <div class="panel-title">
          <h2 class="sidebar-title"><%= get_page_title %></h2>
        </div>
      </div>
    
      <div class="panel-body">
        <ul>
          <% @restaurants.each do |resto| %>
            <li>
              <%= link_to resto.name, resto %>
              (<%= link_to resto.cuisine, 
                   cuisine_restaurants_path(resto.cuisine.downcase) %>)
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>  <!-- col-lg-4 -->
  
  <div class="col-lg-8 col-lg-pull-4">

  <% @restaurants.each do |resto| %>
  <div class="panel resto-panel">
    <div class="panel-heading resto-panel-heading">
      <div class="panel-title">
        <h2 class="resto-title">
          <%= link_to resto.name, resto, class: "resto-title-link" %>
        </h2>
      </div>
    </div>
    <div class="panel-body restaurant-info">
      <strong>Address: </strong><%= resto.address %><br />
      <strong>Telephone number: </strong><%= resto.telephone_number %><br />
      <strong>Cuisine: </strong><%= resto.cuisine %><br />
      
      <br />
      <span class="glyphicon glyphicon-star resto-star" aria-hidden="true"></span>
        <%= resto.stars_count %><br />
    </div>
  </div>
  
  <% end %>

  <% if pagination_shown? %>
    <div class="resto_pagination">
      <%= will_paginate @restaurants %>
    </div>
  <% end %>
  
  </div>  <!-- col-lg-8 -->
  
</div>    

app/views/restaurants/new.html.erb
<% content_for(:title) do %>
  Add New Restaurant
<% end %>

<h2>Add New Restaurant</h2>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<% content_for(:title) do %>
  <%= @restaurant.name %>
<% end %>

<div class="row">
    <div class="col-lg-8">

<div class="panel resto-panel">
  <div class="panel-heading resto-panel-heading">
    <div class="panel-title">
      <h2 class="resto-title"><%= @restaurant.name %>
      </h2>
    </div>
  </div>
  <div class="panel-body restaurant-info">
    <strong>Address: </strong><%= @restaurant.address %><br />
    <strong>Telephone number: </strong><%= @restaurant.telephone_number %><br />
    <strong>Cuisine: </strong><%= @restaurant.cuisine %><br />
    
    <br />
    <span class="glyphicon glyphicon-star resto-star" aria-hidden="true"></span>
    <%= @restaurant.starring_users.size %> <br />
    
    <% if user_signed_in? %>
      <% if current_user.starred_restaurants.include?(@restaurant) %>
        <%= link_to unstar_restaurant_path(@restaurant), method: :delete,
              class: "btn-sm btn-success", id: 'btn-take-star' do %>
          Take <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <% end %>
        
      <% else %>
        <%= link_to star_restaurant_path(@restaurant), method: :patch,
              class: "btn-sm btn-success", id: 'btn-give-star' do %>
          Give <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <% end %>
        
      <% end %>
    <% end %>
  </div>
  
  <% if user_submitted_restaurant?(@restaurant) %>
    <div class="panel-footer">
      <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant),
            class: "btn btn-primary" %>
      <%= link_to "Delete Restaurant", @restaurant, method: :delete,
            class: "btn btn-danger",
            data: { confirm:  "Are you sure you want to delete this restaurant?" } %>
    </div>
  <% end %>
  
</div>

      
  </div>  
</div>        
        